import re

class Lol:
    
    variable_identifier = '^[a-zA-Z][a-zA-Z0-9_]*$'
    function_identifier = '^[a-zA-Z][a-zA-Z0-9_]*$'
    loop_identifier = '^[a-zA-Z][a-zA-Z0-9_]*$'
 
    numbr_literal = '^(-?[0-9]+)$'
    numbar_literal = '^(-)?[0-9]*(\.)[0-9]+$'
    yarn_literal = '^\“.*\”$'
    troof_literal = '^(WIN|FAIL)$' 
    type_literal = '^(NOOB|NUMBR|NUMBAR|YARN|TROOF)$'

    hai_keyword = '^HAI$'
    kthxbye_keyword = '^KTHXBYE$'
    btw_keyword = '^BTW$'
    obtw_keyword = '^OBTW$'
    tldr_keyword = '^TLDR$'
    iHasA_keyword = '^I HAS A$' 
    itz_keyword = '^ITZ$'
    r_keyword = '^R$'
    sumOf_keyword = '^SUM OF$'
    diffOf_keyword = '^DIFF OF$'
    produktOf_keyword = '^PRODUKT OF'
    quoshntOf_keyword = '^QUOSHUNT OF$'
    modOf_keyword = '^MOD OF$'
    biggrOf_keyword = '^BIGGR OF$'
    smallrOf_keyword = '^SMALLR OF$' 
    bothOf_keyword = '^BOTH OF$'
    eitherOf_keyword = '^EITHER OF$'
    wonOf_keyword = '^WON O$'
    not_keyword = '^NOT$'
    anyOf_keyword = '^ANY OF$'
    allOf_keyword = '^ALL OF$'
    bothSaem_keyword = '^BOTH SAEM$'
    diffrint_keyword = '^DIFFRINT$'
    smoosh_keyword = '^SMOOSH$'
    maek_keyword = '^MAEK$'
    a_keyword = '^A$'
    isNowA_keyword = '^IS NOW A$'
    visible_keyword = '^VISIBLE$'
    gimmeh_keyword = '^GIMMEH$'
    oRly_keyword = '^O RLY?$'
    yaRly_keyword = '^YA RLY$'
    mebbe_keyword = '^MEBBE$'
    noWai_keyword = '^NO WAI$'
    oic_keyword = '^OIC$'
    wtf_keyword = '^WTF?$'
    omg_keyword = '^OMG$'
    omgWtf_keyword = '^OMGWTF$'
    imInYr_keyword = '^IM IN YR$'
    uppin_keyword = '^UPPIN$'
    nerfin_keyword = '^NERFIN$'
    yr_keyword = '^YR$'
    til_keyword = '^TIL$'
    wile_keyword = '^WILE$'
    imOuttaYr_keyword = '^IM OUTTA YR$'