HAI
    DIFF OF 3 AN 5
    VISIBLE IT
    PRODUKT OF 3 AN 5
    VISIBLE IT
    SUM OF SUM OF 5 AN 3 AN 5
    VISIBLE IT
    QUOSHUNT OF 5 AN 3
    VISIBLE IT
    MOD OF 5 AN 3
    VISIBLE IT
    BIGGR OF 5 AN 2
    VISIBLE IT
    SMALLR OF SUM OF 2 AN 5 AN 3
    VISIBLE IT
KTHXBYE