HAI
    BOTH SAEM 5 AN 5
    DIFFRINT 5.5 AN 5
    BOTH SAEM 3 AN BIGGR OF 5 AN 6
    BOTH SAEM 3 AN SMALLR OF 5 AN 6
    DIFFRINT 3 AN BIGGR OF 5 AN 6
    DIFFRINT 3.5 AN SMALLR OF 5.1 AN 6.2
KTHXBYE