HAI
    I HAS A x ITZ WIN
    I HAS A y ITZ FAIL
    I HAS A z ITZ FAIL
    BOTH OF EITHER OF WIN AN WIN AN FAIL
    VISIBLE IT
    EITHER OF WIN AN FAIL
    VISIBLE IT
    WON OF WIN AN FAIL
    VISIBLE IT
    NOT WIN
    VISIBLE IT
    ALL OF NOT x AN BOTH OF y AN z AN EITHER OF x AN y MKAY
    VISIBLE IT
KTHXBYE