HAI
    BOTH SAEM 5 AN 5
    VISIBLE IT
    DIFFRINT 5.5 AN 5
    VISIBLE IT
    BOTH SAEM 3 AN BIGGR OF 5 AN 6
    VISIBLE IT
    BOTH SAEM 3 AN SMALLR OF 5 AN 6
    VISIBLE IT
    DIFFRINT 3 AN BIGGR OF 5 AN 6
    VISIBLE IT
    DIFFRINT 3.5 AN SMALLR OF 5.1 AN 6.2
    VISIBLE IT
KTHXBYE